name: Deploy ARM Template

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0

    - name: Login to Azure
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.CLIENTID }}
        password: ${{ secrets.CLIENTSECRET }}
        tenant: ${{ secrets.TENANT_ID }}

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1.0.8
      with:
        scope: resourcegroup
        resource-group: 'monday'
        template: 'ArmTemplate/container-webapp-template.json'
        deploymentMode: Incremental

