name: First Workflow
on:
  issues:
    types: [opened]

jobs:
  twosteps:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "step1"

      - name: Step 2
        run: echo "step2"
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    needs: twosteps

    steps:
        - name: Ship it
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: 'ship ship ship!'
            color: 'red'
